stages:
  - create-env
  - build-app
  - unit-test
  - security-scan
  - build-image
  - update-tag-stag
  - approval
  - update-tag-prod

variables:
  IMAGE_NAME: "valiant/valiant-frontend"
  STAGING_VERSION: "build-$CI_COMMIT_SHORT_SHA"

# Caching Build
.npm-cache:
  image: harbor.pln.co.id/library/node:20-alpine
  cache:  # Cache modules in between jobs
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
      - node_modules/
  before_script:
    - npm install --cache .npm --prefer-offline

prepare_env_file_stg:
  stage: create-env
  image: harbor.pln.co.id/library/hashicorp/vault:1.13.1
  script:
    # Masuk ke Vault untuk autentikasi
    - echo "Authenticating to Vault..."
    - export VAULT_ADDR=$VAULT_ADDR
    - vault login -method=userpass username="$VAULT_USERNAME" password="$VAULT_PASSWORD"
    
    # Mengambil data dari Vault dan menyimpannya ke file .env.development
    - echo "Fetching secrets from Vault..."
    - vault kv get -mount="valiant-staging" "frontend-env-secret" > kv.secret
    - awk '/====== Data ======/{flag=1; next} /======/{flag=0} flag && $1 !~ /---/ && $1 != "" {print $1 "=" $2}' kv.secret > .env.development
  artifacts:
    paths:
      - .env.development
    expire_in: 1 hour
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging" && $CI_PIPELINE_SOURCE == "push"'
      when: always

prepare_env_file_prod:
  stage: create-env
  image: harbor.pln.co.id/library/hashicorp/vault:1.13.1
  script:
    # Masuk ke Vault untuk autentikasi
    - echo "Authenticating to Vault..."
    - export VAULT_ADDR=$VAULT_ADDR
    - vault login -method=userpass username="$VAULT_USERNAME" password="$VAULT_PASSWORD"
    
    # Mengambil data dari Vault dan menyimpannya ke file .env
    - echo "Fetching secrets from Vault..."
    - vault kv get -mount="kv-valiant" "prod-valiant-frontend" > kv.secret
    - awk '/====== Data ======/{flag=1; next} /======/{flag=0} flag && $1 !~ /---/ && $1 != "" {print $1 "=" $2}' kv.secret > .env.production
  artifacts:
    paths:
      - .env.production
  rules:
    - if: '$CI_COMMIT_TAG != null'
      when: always

build-app:
  extends: .npm-cache
  stage: build-app
  script:
    - npm run build:development
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" && $CI_COMMIT_TAG == null'
      when: always
    - if: '$CI_COMMIT_BRANCH == "staging" && $CI_COMMIT_TAG == null'
      when: always


unit-test:
  extends: .npm-cache
  stage: unit-test
  script:
    - npm run coverage
  allow_failure: true
  artifacts:
    when: always
    paths:
      - coverage/
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" && $CI_COMMIT_TAG == null'
      when: always
    - if: '$CI_COMMIT_BRANCH == "staging" && $CI_COMMIT_TAG == null'
      when: always

sonarqube-check:
  stage: security-scan
  image:
    name: harbor.pln.co.id/library/sonarqube-scanner:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - |
      if [ "$CI_COMMIT_BRANCH" == "dev" ]; then
        SONAR_BRANCH="dev"
      elif [ "$CI_COMMIT_BRANCH" == "staging" ]; then
        SONAR_BRANCH="staging"
      else
        SONAR_BRANCH="$CI_COMMIT_BRANCH"
      fi
      sonar-scanner -Dsonar.branch.name=$SONAR_BRANCH
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" && $CI_COMMIT_TAG == null'
      when: always
    - if: '$CI_COMMIT_BRANCH == "staging" && $CI_COMMIT_TAG == null'
      when: always

fortify-sast-scancentral:
  stage: security-scan
  image: harbor.pln.co.id/library/fortify-ci-tools:latest-jdk-21
  variables:
    SCANCENTRAL_BUILD_OPTS: "-bt none"
  script:
    - |
      #!/bin/bash

      if [ "$CI_COMMIT_BRANCH" == "dev" ]; then
        SSC_PV="dev_fe"
      else
        SSC_PV="stg_fe"
      fi

      cekstatusjob="$SSC_URL/api/v1/cloudjobs?projectName=$SSC_APP&pvName=$SSC_PV"

      runstatusjob=$(curl --insecure -s -X GET \
          -H "Authorization: FortifyToken ${API_KEY}" \
          -H "Content-Type: application/json" \
          "$cekstatusjob")

      echo "$runstatusjob"

      # Ambil semua token dan status dengan nama dan versi aplikasi yang sama
      job_tokens=($(echo "$runstatusjob" | grep -oP '"jobToken":"\K[0-9a-fA-F\-]{36}'))
      job_states=($(echo "$runstatusjob" | grep -oP '"jobState":"\K[^"]+'))
      job_app=($(echo "$runstatusjob" | grep -oP '"projectName":"\K[^"]+'))
      job_pvnames=($(echo "$runstatusjob" | grep -oP '"pvName":"\K[^"]+'))
      job_cancellable=($(echo "$runstatusjob" | grep -oP '"jobCancellable":\K(true|false)'))

      # Gabungkan token dan status berdasarkan urutan kemunculan
      active_tokens=()
      for i in "${!job_tokens[@]}"; do
        token="${job_tokens[$i]}"
        state="${job_states[$i]}"
        app="${job_app[$i]}"
        pvname="${job_pvnames[$i]:-}"
        cancellable="${job_cancellable[$i]:-false}"

        if [[ "$app" == "$SSC_APP" ]] && \
           [[ "$pvname" == "$SSC_PV" ]] && \
           { [[ "$state" == "PENDING" ]] || [[ "$state" == "QUEUED" ]] || [[ "$state" == "SCAN_RUNNING" ]]; } && \
           [[ "$cancellable" == "true" ]]; then
           active_tokens+=("$token")
        fi
      done

      if [[ ${#active_tokens[@]} -gt 0 ]]; then
        echo "Ditemukan job active untuk $SSC_APP/$SSC_PV:"
        printf '%s\n' "${active_tokens[@]}"

        for token in "${active_tokens[@]}"; do
          echo "Cancel job token: $token ..."
          cekdelete="$SSC_URL/api/v1/cloudjobs/action/cancel"
          payload="{\"jobTokens\": [\"$token\"]}"
          rundelete=$(curl --insecure -s -X POST \
            -H "Authorization: FortifyToken ${API_KEY}" \
            -H "Content-Type: application/json" \
            -d "$payload" \
            "$cekdelete")
        done

        echo "Menunggu 15 detik untuk memastikan job dicancel..."
        sleep 15
      else
        echo "Tidak ada job active untuk aplikasi ini."
      fi

      # Jalankan perintah scancentral dan tangkap outputnya
      output=$(scancentral -sscurl $SSC_URL -ssctoken $SSC_TOKEN start $SCANCENTRAL_BUILD_OPTS -upload -application $SSC_APP -version $SSC_PV -uptoken $SSC_TOKEN $SSC_EXCLUDES 2>&1)

      # Tampilkan seluruh output untuk debugging
      echo "Log Output:"
      echo "$output"

      # Pola regex untuk menangkap token
      # lama----- pattern='Submitted job and received token:\s*([a-f0-9\-]+)'
      pattern='Submitted job and received token:\s+([0-9a-fA-F\-]{36})'

      # Gunakan grep untuk ekstraksi jika regex BASH tidak cocok
      if [[ $output =~ $pattern ]]; then
          token="${BASH_REMATCH[1]}"
          echo "Job Token: $token"
      else
          token=$(echo "$output" | grep -oP '(?<=Submitted job and received token:\s*)[a-f0-9\-]+')
          
          if [[ -n "$token" ]]; then
              echo "Job Token (grep method): $token"
          else
              echo "No match found."
          fi
      fi
      # Next Step: Cek Status Scan via API
      cek_sast_api="$SSC_URL/api/v1/cloudjobs/$token"
      jobState="PENDING"
      echo "$jobState"

      echo "Menunggu hasil scan..."
      sleep 120
      # Loop untuk mengecek status scan sampai selesai
      while [[ "$jobState" == "PENDING" || "$jobState" == "SCAN_RUNNING" ]]; do
          sleep 30  # Tunggu 30 detik sebelum melakukan pengecekan ulang
          # Panggil API untuk mendapatkan status scan
          runstatus=$(curl --insecure -s -X GET \
            -H "Authorization: FortifyToken $API_KEY" \
            -H "Content-Type: application/json" \
            "$cek_sast_api" -v)
          #echo "Status status: $runstatus"
          # Ambil status dari response API
          jobState=$(echo "$runstatus" | grep -oP '"jobState":"\K[^"]+')
          # Tampilkan status terkini
          echo "Status Scan: $jobState"
      done
      echo "Scan selesai dengan status: $jobState"
      pvId=$(echo "$runstatus" | grep -oP '"pvId":\K\d+')
      pvName=$(echo "$runstatus" | grep -oP '"pvName":"\K[^"]+')
      projectName=$(echo "$runstatus" | grep -oP '"projectName":"\K[^"]+')

      echo "Project Version ID: $pvId"
      echo "Project Version Name: $pvName"
      echo "Project Name: $projectName"

      cekssc="$SSC_URL/api/v1/projectVersions/$pvId/issueSummaries?seriestype=ISSUE_FRIORITY&groupaxistype=ISSUE_FRIORITY"
      runscan=$(curl --insecure -s -X GET \
            -H "Authorization: FortifyToken ${API_KEY}" \
            -H "Content-Type: application/json" \
            "$cekssc")
      critical=$(echo "$runscan" | grep -oP '"Critical","y":\K[0-9]+' || echo 0)
      high=$(echo "$runscan" | grep -oP '"High","y":\K[0-9]+' || echo 0)
      medium=$(echo "$runscan" | grep -oP '"Medium","y":\K[0-9]+' || echo 0)
      low=$(echo "$runscan" | grep -oP '"Low","y":\K[0-9]+' || echo 0)
      total_issue=$(echo "$runscan" | grep -oP '"totalIssueCount":\K[0-9]+' || echo 0)

      echo "Critical: $critical"
      echo "High: $high"
      echo "Medium: $medium"
      echo "Low: $low"
      echo "Total Issue Count: $total_issue"

      echo "Untuk detail vulnerability dapat dilihat pada: $SSC_URL/html/ssc/version/$pvId/audit"
      
      if [[ "$critical" -gt $SAST_CRITICAL_THRESHOLD ]]; then
            echo "ERROR: Jumlah isu Critical ($critical) melebihi batas! Pipeline dihentikan."
            exit 1
      elif [[ "$high" -gt $SAST_HIGH_THRESHOLD ]]; then
            echo "ERROR: Jumlah isu High ($high) melebihi batas! Pipeline dihentikan."
            exit 1
      fi
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" && $CI_COMMIT_TAG == null'
      when: always
    - if: '$CI_COMMIT_BRANCH == "staging" && $CI_COMMIT_TAG == null'
      when: always

fortify-sca:
  stage: security-scan
  image: harbor.pln.co.id/library/openjdk-21:1.21
  script:
    - |
      echo "=== Jalankan SCA Scan dengan Nexus IQ CLI ==="

      if [ "$CI_COMMIT_BRANCH" == "dev" ]; then
        ID_APP="valiant_dev_fe"
      else
        ID_APP="valiant_stg_fe"
      fi

      out=$(java -jar ./nexus-iq-cli.jar \
        -i "$ID_APP" \
        -s "$SCA_URL" \
        -a "$SCA_TOKEN" \
        package-lock.json 2>&1)

      echo "$out"

      critical=$(echo "$out" | grep -Eo 'Number of open policy violations: [0-9]+ critical' | grep -Eo '[0-9]+' | head -n1 || echo 0)
      severe=$(echo "$out" | grep -Eo "$critical critical, [0-9]+ severe" | grep -Eo '[0-9]+ severe' | grep -Eo '[0-9]+' | head -n1 || echo 0)
      moderate=$(echo "$out" | grep -Eo "$severe severe, [0-9]+ moderate" | grep -Eo '[0-9]+ moderate' | grep -Eo '[0-9]+' | head -n1 || echo 0)

      echo "High: $critical"
      echo "Medium: $severe"
      echo "Low: $moderate"

      url=$(echo "$out" | grep -Eo 'The detailed report can be viewed online at .*' | grep -Eo 'https?://[^[:space:]]+' | head -n1 || echo "")

      echo "Untuk detail vulnerability dapat dilihat pada: $url"
      
      if [[ "$critical" -gt $SCA_CRITICAL_THRESHOLD ]]; then
            echo "ERROR: Jumlah isu High ($critical) melebihi batas! Pipeline dihentikan."
            exit 1
      elif [[ "$severe" -gt $SCA_HIGH_THRESHOLD ]]; then
            echo "ERROR: Jumlah isu Medium ($severe) melebihi batas! Pipeline dihentikan."
            exit 1
      fi
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" && $CI_COMMIT_TAG == null'
      when: always
    - if: '$CI_COMMIT_BRANCH == "staging" && $CI_COMMIT_TAG == null'
      when: always

build-image:
  image: 
    name: harbor.pln.co.id/library/docker:24.0.7
  stage: build-image
  needs:
    - job: build-app
    - job: prepare_env_file_stg
      optional: true
    - job: prepare_env_file_prod
      optional: true
    - job: sonarqube-check
      optional: true
  services:
    - harbor.pln.co.id/library/docker:24.0.7-dind
  variables:
    DOCKER_HOST: "tcp://localhost:2375"
  before_script:
    - update-ca-certificates
    - export IMAGE_FULL=$HARBOR_REGISTRY/$IMAGE_NAME:$STAGING_VERSION
    - if [[ $CI_COMMIT_TAG != '' ]]; then export IMAGE_FULL=$HARBOR_REGISTRY/$IMAGE_NAME:$CI_COMMIT_TAG; fi;
  script:
    - docker login -u $HARBOR_REGISTRY_USERNAME -p $HARBOR_REGISTRY_PASSWORD $HARBOR_REGISTRY
    - echo "Building Image $IMAGE_FULL"
    - docker build --build-arg BUILD_SCRIPT=build:development -t $IMAGE_FULL .
    - docker push $IMAGE_FULL
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging" && $CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: '$CI_COMMIT_TAG != null'
      when: always

deploy-stag:
  image:
    name : harbor.pln.co.id/library/alpine:git
    entrypoint : [""]
  stage: update-tag-stag
  needs:
    - build-image
  before_script:
    - git config --global user.name "Gitlab PLN CI/CD"
    - git config --global user.email "gitlab@pln.co.id"
    - git config --global http.sslVerify false
  script:
    - echo "Updating Deployment Repository with tag $STAGING_VERSION"
    - git clone $DEPLOYMENT_REPOSITORY .manifest
    - cd .manifest/environments
    - |
      frontend_tag=$(cat values-stag.yaml | grep -m 1 frontendTag: | awk '{print $2}')
    - |
      version=$(cat values-stag.yaml | grep -m 1 version: | awk '{print $2}')
    - |
      sed -i "s/frontendTag: $frontend_tag/frontendTag: $STAGING_VERSION/g" values-stag.yaml
    - |
      sed -i "s/version: $version/version: $STAGING_VERSION/g" values-stag.yaml
    - git commit -am "Update Deployment Image Version to version $STAGING_VERSION" && git push origin master
  retry: 2
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging" && $CI_PIPELINE_SOURCE == "push"'
      when: on_success

send-approval-notif:
  stage: approval
  image:
    name: harbor.pln.co.id/library/email-service:latest
    entrypoint: [""]
  script:
    - cd /app
    - python ./email_sender.py --template approval.html --from $MAIL_FROM_ADDRESS --to $APPROVAL_1_EMAIL --subject "CI/CD Deployment Need Approval"
    - python ./email_sender.py --template approval.html --from $MAIL_FROM_ADDRESS --to $APPROVAL_2_EMAIL --subject "CI/CD Deployment Need Approval"
    - python ./email_sender.py --template approval.html --from $MAIL_FROM_ADDRESS --to $APPROVAL_3_EMAIL --subject "CI/CD Deployment Need Approval"
  rules:
    - if: '$CI_COMMIT_TAG =~ /.*-release$/'
      when: always

approval_project_manager:
  stage: approval
  dependencies: []
  script:
    - if [[ "$GITLAB_USER_EMAIL" == "$APPROVAL_1_EMAIL" ]]; then
        echo "User has permission to run the job.";
      else
        echo "User does not have permission to run the job. Aborting...";
        exit 1;
      fi;
  # when: manual
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_TAG =~ /.*-release$/'
      when: manual

approval_security_engineer:
  stage: approval
  dependencies: []
  script:
    - if [[ "$GITLAB_USER_EMAIL" == "$APPROVAL_2_EMAIL" ]]; then
        echo "User has permission to run the job.";
      else
        echo "User does not have permission to run the job. Aborting...";
        exit 1;
      fi;
  # when: manual
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_TAG =~ /.*-release$/'
      when: manual

approval_sre:
  stage: approval
  dependencies: []
  script:
    - if [[ "$GITLAB_USER_EMAIL" == "$APPROVAL_3_EMAIL" ]]; then
        echo "User has permission to run the job.";
      else
        echo "User does not have permission to run the job. Aborting...";
        exit 1;
      fi;
  # when: manual
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_TAG =~ /.*-release$/'
      when: manual

deploy-prod:
  image:
    name : harbor.pln.co.id/library/alpine:git
    entrypoint : [""]
  stage: update-tag-prod
  needs:
   - approval_project_manager
   - approval_security_engineer
   - approval_sre
  dependencies: []
  before_script:
    - git config --global user.name "Gitlab Btech CI/CD"
    - git config --global user.email "gitlab@gitlab.btech-sd.id"
    - git config --global http.sslVerify false
  script:
    - echo "Updating Production Repository with tag $CI_COMMIT_TAG"
    - git clone $DEPLOYMENT_REPOSITORY .manifest
    - cd .manifest/environments
    - git checkout production
    - |
      frontend_tag=$(cat values-prod.yaml | grep -m 1 frontendTag: | awk '{print $2}')
    - |
      version=$(cat values-prod.yaml | grep -m 1 version: | awk '{print $2}')
    - |
      sed -i "s/frontendTag: $frontend_tag/frontendTag: $CI_COMMIT_TAG/g" values-prod.yaml
    - |
      sed -i "s/version: $version/version: $CI_COMMIT_TAG/g" values-prod.yaml
    - git commit -am "Update Production Image Version to version $CI_COMMIT_TAG" && git push origin production
  retry: 2
  rules:
    - if: '$CI_COMMIT_TAG =~ /.*-release$/'
      when: on_success
      