server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Jangan tampilkan informasi server
    server_tokens off;

    # Tambahkan header keamanan
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-XSS-Protection "1; mode=block";
    add_header Content-Security-Policy "default-src 'self'";

    # Harden akses file
    location / {
        try_files $uri /index.html;
    }

    location ~* \.(log|txt|md|json|xml|yaml|yml|sh)$ {
        deny all;
    }
}