sonar.projectKey=valiant-frontend
sonar.qualitygate.wait=true
sonar.junit.reportPaths=./reports/junitt__/unit
sonar.test.inclusions=*/.test.ts,*/.spec.ts
sonar.exclusions=*/node_modules/*
sonar.coverage.exclusions=*/.test.ts
sonar.host.url=https://sonarqube.pln.co.id
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.junit.reportPaths=./reports/junit
